# Tidy Data in Python
The examples and code in this notebook are made by [Jean-Nicholas Hould](http://www.jeannicholashould.com/)

Detailed explanations for important code snippets are provided by Mervat Abuelkheir as part of the CSEN1095 Data Engineering Course.

The goal of this notebook is to show how a messy dataset can be tidied into proper rows representing objects, columns representing attributes, and cells representing scalar values.

Pay attention to the <span style="color:red"> <b> paragraphs in bold red</b></span>; they ask you to do something and provide input!

First thing we need to do is import some libraries.

In [1]:
import pandas as pd
import datetime # to handle date/time attributes
from os import listdir # os is a module for interacting with the OS
from os.path import isfile, join # to verify file object, and concatenate paths
import glob # to find pathnames matching a specific pattern
import re # regular expressions :)

## Examining the datasets

In this part of the exercise we will import a number of datasets and examine their structure to verify if the datasets are tidy.

Remember the requirements for a tidy dataset:
<br> 1- Each row describes a single object
<br> 2- Each column describes a property/attribute of that object
<br> 3- Column values have the same measurement unit
<br> 4- Columns contain atomic/scalar values (no multiple values per table cell)

For each dataset imported, test your ability to identify is it is tidy or not.

### Dataset 1: Pew Research Center

Pew Research Center is a famous center in the US that performs polling surveys on citizens. This is example data about the breakdown of yearly income per religion.

In [4]:
df = pd.read_csv("./data/pew-raw.csv")
df

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k
0,Agnostic,27,34,60,81,76,137
1,Atheist,12,27,37,52,35,70
2,Buddhist,27,21,30,34,33,58
3,Catholic,418,617,732,670,638,1116
4,Dont know/refused,15,14,15,11,10,35
5,Evangelical Prot,575,869,1064,982,881,1486
6,Hindu,1,9,7,9,11,34
7,Historically Black Prot,228,244,236,238,197,223
8,Jehovahs Witness,20,27,24,24,21,30
9,Jewish,19,19,25,25,30,95

<span style="color:red"> <b> What are the attributes of interest? How are they organized? Is the dataset tidy? </b></span> 
    
You can brainstorm your thought process and document in a new cell if you like.
<br>Instructions for beginners:
<br>- Add a new cell from the notebook menu above (+ button).
<br>- Double click anywhere inside the new cell to enter edit mode.
<br>- When done, press CTRL+ENTER or SHIFT+ENTER to commit content.
<br>- You can edit content anytime by double clicking inside the cell.

## Let's tidy the dataset!

The melt function is used to change the format of a pandas data frame from wide to long, assigning one column as an identifier and "unpivoting" the others.

In [5]:
# melt method takes as input a dataframe, one or more identifier attributes, one or more attribute names, and value attribute 
# define new pandas dataframe, religion column will be identifier attribute
# values spread across multiple column headers of income ranges will be unpivoted into new attribute "income"
# actual frequencies of citizens with specific income range will be unpivoted into new attribute "freq"
formatted_df = pd.melt(df,["religion"], var_name="income", value_name="freq")
formatted_df = formatted_df.sort_values(by=["religion"]) # just sorting the new table by religion attribute
formatted_df.head(50) # show first 10 rows

                    religion    income  freq
0                   Agnostic     <$10k    27
30                  Agnostic   $30-40k    81
40                  Agnostic   $40-50k    76
50                  Agnostic   $50-75k   137
10                  Agnostic   $10-20k    34
20                  Agnostic   $20-30k    60
41                   Atheist   $40-50k    35
21                   Atheist   $20-30k    37
11                   Atheist   $10-20k    27
31                   Atheist   $30-40k    52
1                    Atheist     <$10k    12
51                   Atheist   $50-75k    70
42                  Buddhist   $40-50k    33
2                   Buddhist     <$10k    27
12                  Buddhist   $10-20k    21
32                  Buddhist   $30-40k    34
52                  Buddhist   $50-75k    58
22                  Buddhist   $20-30k    30
43                  Catholic   $40-50k   638
33                  Catholic   $30-40k   670
23                  Catholic   $20-30k   732
53                  Catholic   $50-75k  1116
13                  Catholic   $10-20k   617
3                   Catholic     <$10k   418
24         Dont know/refused   $20-30k    15
44         Dont know/refused   $40-50k    10
4          Dont know/refused     <$10k    15
54         Dont know/refused   $50-75k    35
14         Dont know/refused   $10-20k    14
34         Dont know/refused   $30-40k    11
25         Evangelical Prot    $20-30k  1064
55         Evangelical Prot    $50-75k  1486
15         Evangelical Prot    $10-20k   869
5          Evangelical Prot      <$10k   575
45         Evangelical Prot    $40-50k   881
35         Evangelical Prot    $30-40k   982
56                    Hindu    $50-75k    34
26                    Hindu    $20-30k     7
46                    Hindu    $40-50k    11
16                    Hindu    $10-20k     9
36                    Hindu    $30-40k     9
6                     Hindu      <$10k     1
47  Historically Black Prot    $40-50k   197
37  Historically Black Prot    $30-40k   238
57  Historically Black Prot    $50-75k   223
27  Historically Black Prot    $20-30k   236
17  Historically Black Prot    $10-20k   244
7   Historically Black Prot      <$10k   228
8          Jehovahs Witness      <$10k    20
38         Jehovahs Witness    $30-40k    24

<span style="color:red"> <b> Why do the indices that are added automatically by pandas appear out of order? </b></span> 
<br>(Just a question to let you think of how pandas dataframes are indexed.)

### Dataset 2: Billboard Top 100

This dataset outlines data about the top hit songs on the Billboard list.

In [67]:
df = pd.read_csv("./data/billboard.csv", encoding="mac_latin2")
df.head(10)

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2000,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2000,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2000,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,81,54.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
new_df = df

<span style="color:red"> <b> Again: What are the attributes of interest? How are they organized? Is the dataset tidy? </b></span>

The structure of the dataset is more complex than the previous one, and it is not immediately clear what a typical row should represent or look like. Answering the above questions helps you frame the data better. 
<br>You can brainstorm your thought process and document in a new cell if you like.

## Let's tidy the dataset!

One way a record could be organized is to make it represent the rank of each song in every week the song was on the Billboard list. This omits the need to keep track of all 76 weeks data, which is null for most of the songs.

A record would have data about the year, artist, track, time, genre, week, rank, and date.

The unique identifier is no single attribute, as one artist can have the track on the billboards at the same year, genre, and time. The only difference would be the week, rank, and date (since date is correlated with week). Therefore, to identify a track's rank and week, we need to use the year, artist, track, time, genre, and date as a combined unique identifier.

### <span style="color:blue"> Note on conversions in Python</span>

<span style="color:blue"> The following conversions are accepted by Python:</span>
<br><span style="color:blue"> - passing a string representation of an integer into int</span>
<br><span style="color:blue"> - passing a string representation of a float into float</span>
<br><span style="color:blue"> - passing a string representation of an integer into float</span>
<br><span style="color:blue"> - passing an integer into float</span>
<br><span style="color:blue"> - passing a float into int</span>

<span style="color:blue"> You get an error if you pass a string representation of a float (or anything other than an integer) into int</span>
<br><span style="color:blue"> This is especially problematic if you have NaN values that are float and you want to convert them to integers. It does not work using int, and you have to use Int32. </span>

Now back to tidying up the Billboard dataset!

In [68]:
# Melting
# Define unique identifiers in one variable. Include both dates of entry and peak for now; will be merged into one attribute later.
id_vars = ["year","artist.inverted","track","time","genre","date.entered","date.peaked"]
# Now melt structure to have identifiers, variable name (week) and values (rank)
df = pd.melt(frame=df,id_vars=id_vars, var_name="week", value_name="rank")

# Formatting 
# First, for week attribute, extract week number from string representation of week column names and convert to float then to integer
df["week"] = df["week"].str.extract('(\d+)', expand=False).astype(float).astype('Int32') 
# Second, extract rank values and convert them to integer
df["rank"] = df["rank"].astype('Int32')

# Cleaning out unnecessary rows
df = df.dropna()
df.head(10)
# Create "date" columns
# Date for each week is date the track entered the billboard + number of weeks passed for an entry
# Example: if date entered is 26/02/2000, then this is the date for week 1, and the date will change for week 2 to become 04/03/2000, and so on
df["date"] = pd.to_datetime(df["date.entered"]) + pd.to_timedelta(df["week"], unit='w') - pd.DateOffset(weeks=1)


# Frame the final tidy data, replacing the dates of entry and peak with only the date, then sort by the identifiers
final_df = df[["year", "artist.inverted", "track", "time", "genre", "week", "rank", "date"]]
final_df = final_df.sort_values(ascending=True, by=["year","artist.inverted","track","week","rank"])

# Assigning the tidy dataset to a variable for future usage
billboard = final_df

In [69]:
billboard

,year,artist.inverted,track,time,genre,week,rank,date
246,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,1,87,2000-02-26
563,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,2,82,2000-03-04
880,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,3,72,2000-03-11
1197,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,4,77,2000-03-18
1514,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,5,87,2000-03-25
1831,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,6,94,2000-04-01
2148,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,7,99,2000-04-08
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,1,91,2000-09-02
604,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2,87,2000-09-09
921,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,3,92,2000-09-16
24,2000,3 Doors Down,Kryptonite,3:53,Rock,1,81,2000-04-08
341,2000,3 Doors Down,Kryptonite,3:53,Rock,2,70,2000-04-15
658,2000,3 Doors Down,Kryptonite,3:53,Rock,3,68,2000-04-22
975,2000,3 Doors Down,Kryptonite,3:53,Rock,4,67,2000-04-29
1292,2000,3 Doors Down,Kryptonite,3:53,Rock,5,66,2000-05-06
1609,2000,3 Doors Down,Kryptonite,3:53,Rock,6,57,2000-05-13
1926,2000,3 Doors Down,Kryptonite,3:53,Rock,7,54,2000-05-20
2243,2000,3 Doors Down,Kryptonite,3:53,Rock,8,53,2000-05-27
2560,2000,3 Doors Down,Kryptonite,3:53,Rock,9,51,2000-06-03
2877,2000,3 Doors Down,Kryptonite,3:53,Rock,10,51,2000-06-10
3194,2000,3 Doors Down,Kryptonite,3:53,Rock,11,51,2000-06-17
3511,2000,3 Doors Down,Kryptonite,3:53,Rock,12,51,2000-06-24
3828,2000,3 Doors Down,Kryptonite,3:53,Rock,13,47,2000-07-01
4145,2000,3 Doors Down,Kryptonite,3:53,Rock,14,44,2000-07-08
4462,2000,3 Doors Down,Kryptonite,3:53,Rock,15,38,2000-07-15
4779,2000,3 Doors Down,Kryptonite,3:53,Rock,16,28,2000-07-22
5096,2000,3 Doors Down,Kryptonite,3:53,Rock,17,22,2000-07-29
5413,2000,3 Doors Down,Kryptonite,3:53,Rock,18,18,2000-08-05
5730,2000,3 Doors Down,Kryptonite,3:53,Rock,19,18,2000-08-12
6047,2000,3 Doors Down,Kryptonite,3:53,Rock,20,14,2000-08-19
...,...,...,...,...,...,...,...,...
2868,2000,matchbox twenty,Bent,4:12,Rock,10,12,2000-07-01
3185,2000,matchbox twenty,Bent,4:12,Rock,11,8,2000-07-08
3502,2000,matchbox twenty,Bent,4:12,Rock,12,6,2000-07-15
3819,2000,matchbox twenty,Bent,4:12,Rock,13,1,2000-07-22
4136,2000,matchbox twenty,Bent,4:12,Rock,14,2,2000-07-29
4453,2000,matchbox twenty,Bent,4:12,Rock,15,3,2000-08-05
4770,2000,matchbox twenty,Bent,4:12,Rock,16,2,2000-08-12
5087,2000,matchbox twenty,Bent,4:12,Rock,17,2,2000-08-19
5404,2000,matchbox twenty,Bent,4:12,Rock,18,3,2000-08-26
5721,2000,matchbox twenty,Bent,4:12,Rock,19,4,2000-09-02
6038,2000,matchbox twenty,Bent,4:12,Rock,20,5,2000-09-09
6355,2000,matchbox twenty,Bent,4:12,Rock,21,4,2000-09-16
6672,2000,matchbox twenty,Bent,4:12,Rock,22,4,2000-09-23
6989,2000,matchbox twenty,Bent,4:12,Rock,23,6,2000-09-30
7306,2000,matchbox twenty,Bent,4:12,Rock,24,9,2000-10-07
7623,2000,matchbox twenty,Bent,4:12,Rock,25,12,2000-10-14
7940,2000,matchbox twenty,Bent,4:12,Rock,26,13,2000-10-21
8257,2000,matchbox twenty,Bent,4:12,Rock,27,19,2000-10-28
8574,2000,matchbox twenty,Bent,4:12,Rock,28,20,2000-11-04
8891,2000,matchbox twenty,Bent,4:12,Rock,29,20,2000-11-11
9208,2000,matchbox twenty,Bent,4:12,Rock,30,24,2000-11-18
9525,2000,matchbox twenty,Bent,4:12,Rock,31,29,2000-11-25
9842,2000,matchbox twenty,Bent,4:12,Rock,32,28,2000-12-02
10159,2000,matchbox twenty,Bent,4:12,Rock,33,27,2000-12-09
10476,2000,matchbox twenty,Bent,4:12,Rock,34,30,2000-12-16
10793,2000,matchbox twenty,Bent,4:12,Rock,35,33,2000-12-23
11110,2000,matchbox twenty,Bent,4:12,Rock,36,37,2000-12-30
11427,2000,matchbox twenty,Bent,4:12,Rock,37,38,2001-01-06
11744,2000,matchbox twenty,Bent,4:12,Rock,38,38,2001-01-13
12061,2000,matchbox twenty,Bent,4:12,Rock,39,48,2001-01-20

<span style="color:red"><b>Why did we convert the week string to float before converting it to int?</b></span>

because you can't pass a string representation of a float into an integer but you can pass into a float, and then you can pass this float into an int

<span style="color:red"><b>What does the parameter '(\d+)' in the string.extract method do? </b></span>

I think, it extracts the digit from the regular expression

In [6]:
# Now let's check the tidied data frame
# Separating this line of code to avoid running the formatting code multiple times and getting errors
final_df.head(10)

,year,artist.inverted,track,time,genre,week,rank,date
246,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,1,87,2000-02-26
563,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,2,82,2000-03-04
880,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,3,72,2000-03-11
1197,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,4,77,2000-03-18
1514,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,5,87,2000-03-25
1831,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,6,94,2000-04-01
2148,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,7,99,2000-04-08
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,1,91,2000-09-02
604,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2,87,2000-09-09
921,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,3,92,2000-09-16

### Dataset 3: Tubercolosis

This dataset outlines the number of tubercolosis patients in different countries in the year 2000.

A few notes on the raw data set:

- The columns starting with "m" or "f" contain multiple variables: 
    - Sex ("m" or "f")
    - Age Group ("0-14","15-24", "25-34", "45-54", "55-64", "65", "unknown")
- Mixture of 0s and missing values("NaN"). This is due to the data collection process and the distinction is important for this dataset.

In [70]:
df = pd.read_csv("./data/tb-raw.csv")
df

  country  year   m014  m1524   m2534  m3544  m4554  m5564    m65  mu   f014
0      AD  2000    0.0    0.0     1.0    0.0      0      0    0.0 NaN    NaN
1      AE  2000    2.0    4.0     4.0    6.0      5     12   10.0 NaN    3.0
2      AF  2000   52.0  228.0   183.0  149.0    129     94   80.0 NaN   93.0
3      AG  2000    0.0    0.0     0.0    0.0      0      0    1.0 NaN    1.0
4      AL  2000    2.0   19.0    21.0   14.0     24     19   16.0 NaN    3.0
5      AM  2000    2.0  152.0   130.0  131.0     63     26   21.0 NaN    1.0
6      AN  2000    0.0    0.0     1.0    2.0      0      0    0.0 NaN    0.0
7      AO  2000  186.0  999.0  1003.0  912.0    482    312  194.0 NaN  247.0
8      AR  2000   97.0  278.0   594.0  402.0    419    368  330.0 NaN  121.0
9      AS  2000    NaN    NaN     NaN    NaN      1      1    NaN NaN    NaN

<span style="color:red"> <b> Again: What are the attributes of interest? How are they organized? Is the dataset tidy? </b></span>

## Let's tidy the dataset!

Same as what we did before: We need identifiers, we need the column names to represent variables (two in this case, since the column names carry information about gender and age group), and we need the frequency values to be in one column.

In [8]:
# Let's use the year and country as unique identifiers, and name the # of patients as "cases" and the column variables as "sex and age"
df = pd.melt(df, id_vars=["country","year"], value_name="cases", var_name="sex_and_age")

# Extract Sex, Age lower bound and Age upper bound group
tmp_df = df["sex_and_age"].str.extract("(\D)(\d+)(\d{2})", expand=False)    

# tmp_df now has multiple columns corresponding to the strings extracted from the column names. Now name the columns
tmp_df.columns = ["sex", "age_lower", "age_upper"]

# Create "age" column based on "age_lower" and "age_upper"
tmp_df["age"] = tmp_df["age_lower"] + "-" + tmp_df["age_upper"]

# Merge - axis parameter indicates the axis along which merge will take place. 1 means by columns
df = pd.concat([df, tmp_df], axis=1)

# Drop unnecessary columns and rows
df = df.drop(['sex_and_age',"age_lower","age_upper"], axis=1)
# Drop null values
df = df.dropna()
# Sort rows by all four attributes
df = df.sort_values(ascending=True,by=["country", "year", "sex", "age"])
df.head(10)

   country  year  cases sex    age
0       AD  2000    0.0   m   0-14
10      AD  2000    0.0   m  15-24
20      AD  2000    1.0   m  25-34
30      AD  2000    0.0   m  35-44
40      AD  2000    0.0   m  45-54
50      AD  2000    0.0   m  55-64
81      AE  2000    3.0   f   0-14
1       AE  2000    2.0   m   0-14
11      AE  2000    4.0   m  15-24
21      AE  2000    4.0   m  25-34

<span style="color:red"><b>What does the parameter value "(\D)(\d+)(\d{2})" do?</b></span>

### Dataset 4: Global Historical Climatology Network

In [88]:
df = pd.read_csv("./data/weather-raw.csv")
df.head(10)

         id  year  month element  d1    d2    d3  d4    d5  d6  d7  d8
0   MX17004  2010      1    tmax NaN   NaN   NaN NaN   NaN NaN NaN NaN
1   MX17004  2010      1    tmin NaN   NaN   NaN NaN   NaN NaN NaN NaN
2  MX17004   2010      2    tmax NaN  27.3  24.1 NaN   NaN NaN NaN NaN
3   MX17004  2010      2    tmin NaN  14.4  14.4 NaN   NaN NaN NaN NaN
4   MX17004  2010      3    tmax NaN   NaN   NaN NaN  32.1 NaN NaN NaN
5   MX17004  2010      3    tmin NaN   NaN   NaN NaN  14.2 NaN NaN NaN
6   MX17004  2010      4    tmax NaN   NaN   NaN NaN   NaN NaN NaN NaN
7   MX17004  2010      4    tmin NaN   NaN   NaN NaN   NaN NaN NaN NaN
8   MX17004  2010      5    tmax NaN   NaN   NaN NaN   NaN NaN NaN NaN
9   MX17004  2010      5    tmin NaN   NaN   NaN NaN   NaN NaN NaN NaN

In this dataset, variables are stored in both rows and columns. tmax and tmin stand for max and min temperatures for each day. Date is broken down to three columns, with the day being spread across multiple columns. We need the data to represent min and max temperatures per date.

Notice that the dataset has many missing values.

## Let's tidy the dataset!

Same as what we did before: We need identifiers, we need the column names to represent variables (min and max, and date!), and we need the temperature values to be in two columns.

In [89]:
# Let's start first by putting the day values in one column. We will not play with min and max temperatures for now
df = pd.melt(df, id_vars=["id", "year","month","element"], var_name="day_raw", value_name = "trial")
df.head(10)

         id  year  month element day_raw  trial
0   MX17004  2010      1    tmax      d1    NaN
1   MX17004  2010      1    tmin      d1    NaN
2  MX17004   2010      2    tmax      d1    NaN
3   MX17004  2010      2    tmin      d1    NaN
4   MX17004  2010      3    tmax      d1    NaN
5   MX17004  2010      3    tmin      d1    NaN
6   MX17004  2010      4    tmax      d1    NaN
7   MX17004  2010      4    tmin      d1    NaN
8   MX17004  2010      5    tmax      d1    NaN
9   MX17004  2010      5    tmin      d1    NaN

In [11]:
# Extracting day
# df["day"] automatically adds a "day" attribute to the df dataframe
df["day"] = df["day_raw"].str.extract("d(\d+)", expand=False)  
df["id"] = "MX17004"

# Convert year, month, and day to numeric values
# Notice the use of the lamda function to apply one instruction to multiple inputs
df[["year","month","day"]] = df[["year","month","day"]].apply(lambda x: pd.to_numeric(x, errors='ignore'))

# Let's define a function to create a date from the different columns. Function accepts a row of 3 values as input and returns consolidated date
def create_date_from_year_month_day(row):
    return datetime.datetime(year=row["year"], month=int(row["month"]), day=row["day"])

# Define date attribute, by having the temporary lamda function call the create_date function
df["date"] = df.apply(lambda row: create_date_from_year_month_day(row), axis=1)
# Drop the redundant columns used to compute date
df = df.drop(['year',"month","day", "day_raw"], axis=1)
# Now drop the missing values
df = df.dropna()

# Unmelting column "element"
df = df.pivot_table(index=["id","date"], columns="element", values="value")
df.reset_index(drop=False, inplace=True)
df

element       id       date  tmax  tmin
0        MX17004 2010-02-02  27.3  14.4
1        MX17004 2010-02-03  24.1  14.4
2        MX17004 2010-03-05  32.1  14.2

## <span style="color:red"> Exercise your tidying muscles! </span>

<span style="color:red"><b> The GapMinder dataset includes information about the life expectancy, the GDP per capita, and the population of various countries between the years 1952 and 2007.</b></span>

<span style="color:red"> <b>Import the dataset, investigate it to identify what the potential attributes should be, the problems with the current structure, and think of how to tidy the dataset, and then proceed to tidy the dataset.</b></span>

In [118]:
df = pd.read_csv("./data/gapminder.csv")
df

,continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
0,Africa,Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,...,11000948.0,12760499.0,14760787.0,17152804.0,20033753.0,23254956.0,26298373.0,29072015.0,31287142,33333216
1,Africa,Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,...,4826015.0,5247469.0,5894858.0,6162675.0,7016384.0,7874230.0,8735988.0,9875024.0,10866106,12420476
2,Africa,Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,...,2151895.0,2427334.0,2761407.0,3168267.0,3641603.0,4243788.0,4981671.0,6066080.0,7026113,8078314
3,Africa,Botswana,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,...,512764.0,553541.0,619351.0,781472.0,970347.0,1151184.0,1342614.0,1536536.0,1630347,1639131
4,Africa,Burkina Faso,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,...,4919632.0,5127935.0,5433886.0,5889574.0,6634596.0,7586551.0,8878303.0,10352843.0,12251209,14326203
5,Africa,Burundi,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,...,2961915.0,3330989.0,3529983.0,3834415.0,4580410.0,5126023.0,5809236.0,6121610.0,7021078,8390505
6,Africa,Cameroon,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,...,5793633.0,6335506.0,7021028.0,7959865.0,9250831.0,10780667.0,12467171.0,14195809.0,15929988,17696293
7,Africa,Central African Republic,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,...,1523478.0,1733638.0,1927260.0,2167533.0,2476971.0,2840009.0,3265124.0,3696513.0,4048013,4369038
8,Africa,Chad,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,...,3150417.0,3495967.0,3899068.0,4388260.0,4875118.0,5498955.0,6429417.0,7562011.0,8835739,10238807
9,Africa,Comoros,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,...,191689.0,217378.0,250027.0,304739.0,348643.0,395114.0,454429.0,527982.0,614382,710960
10,Africa,Congo Dem. Rep.,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,...,17486434.0,19941073.0,23007669.0,26480870.0,30646495.0,35481645.0,41672143.0,47798986.0,55379852,64606759
11,Africa,Congo Rep.,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,...,1047924.0,1179760.0,1340458.0,1536769.0,1774735.0,2064095.0,2409073.0,2800947.0,3328795,3800610
12,Africa,Cote d'Ivoire,1388.594732,1500.895925,1728.869428,2052.050473,2378.201111,2517.736547,2602.710169,2156.956069,...,3832408.0,4744870.0,6071696.0,7459574.0,9025951.0,10761098.0,12772596.0,14625967.0,16252726,18013409
13,Africa,Djibouti,2669.529475,2864.969076,3020.989263,3020.050513,3694.212352,3081.761022,2879.468067,2880.102568,...,89898.0,127617.0,178848.0,228694.0,305991.0,311025.0,384156.0,417908.0,447416,496374
14,Africa,Egypt,1418.822445,1458.915272,1693.335853,1814.880728,2024.008147,2785.493582,3503.729636,3885.460710,...,28173309.0,31681188.0,34807417.0,38783863.0,45681811.0,52799062.0,59402198.0,66134291.0,73312559,80264543
15,Africa,Equatorial Guinea,375.643123,426.096408,582.841971,915.596003,672.412257,958.566812,927.825343,966.896815,...,249220.0,259864.0,277603.0,192675.0,285483.0,341244.0,387838.0,439971.0,495627,551201
16,Africa,Eritrea,328.940557,344.161886,380.995843,468.794970,514.324208,505.753808,524.875849,521.134133,...,1666618.0,1820319.0,2260187.0,2512642.0,2637297.0,2915959.0,3668440.0,4058319.0,4414865,4906585
17,Africa,Ethiopia,362.146280,378.904163,419.456416,516.118644,566.243944,556.808383,577.860747,573.741314,...,25145372.0,27860297.0,30770372.0,34617799.0,38111756.0,42999530.0,52088559.0,59861301.0,67946797,76511887
18,Africa,Gabon,4293.476475,4976.198099,6631.459222,8358.761987,11401.948410,21745.573280,15113.361940,11864.408440,...,455661.0,489004.0,537977.0,706367.0,753874.0,880397.0,985739.0,1126189.0,1299304,1454867
19,Africa,Gambia,485.230659,520.926711,599.650276,734.782912,756.086836,884.755251,835.809611,611.658861,...,374020.0,439593.0,517101.0,608274.0,715523.0,848406.0,1025384.0,1235767.0,1457766,1688359
20,Africa,Ghana,911.298937,1043.561537,1190.041118,1125.697160,1178.223708,993.223957,876.032569,847.006113,...,7355248.0,8490213.0,9354120.0,10538093.0,11400338.0,14168101.0,16278738.0,18418288.0,20550751,22873338
21,Africa,Guinea,510.196492,576.267025,686.373674,708.759541,741.666231,874.685864,857.250358,805.572472,...,3140003.0,3451418.0,3811387.0,4227026.0,4710497.0,5650262.0,6990574.0,8048834.0,8807818,9947814
22,Africa,Guinea-Bissau,299.850319,431.790457,522.034373,715.580640,820.224588,764.725963,838.123967,736.415392,...,627820.0,601287.0,625361.0,745228.0,825987.0,927524.0,1050938.0,1193708.0,1332459,1472041
23,Africa,Kenya,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,...,8678557.0,10191512.0,12044785.0,14500404.0,17661452.0,21198082.0,25020539.0,28263827.0,31386842,35610177
24,Africa,Lesotho,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,...,893143.0,996380.0,1116779.0,1251524.0,1411807.0,1599200.0,1803195.0,1982823.0,2046772,2012649
25,Africa,Liberia,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,...,1112796.0,1279406.0,1482628.0,1703617.0,1956875.0,2269414.0,1912974.0,2200725.0,2814651,3193942
26,Africa,Libya,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,...,1441863.0,1759224.0,2183877.0,2721783.0,3344074.0,3799845.0,4364501.0,4759670.0,5368585,6036914
27,Africa,Madagascar,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,...,5703324.0,6334556.0,7082430.0,8007166.0,9171477.0,10568642.0,12210395.0,14165114.0,16473477,19167654
28,Africa,Malawi,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,...,3628608.0,4147252.0,4730997.0,5637246.0,6502825.0,7824747.0,10014249.0,10419991.0,11824495,13327079
29,Africa,Mali,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,...,4690372.0,5212416.0,5828158.0,6491649.0,6998256.0,7634008.0,8416215.0,9384984.0,10580176,12031795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Europe,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,...,9218400.0,9556500.0,9709100.0,9821800.0,9856303.0,9870200.0,10045622.0,10199787.0,10311970,10392226
113,Europe,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,...,3349000.0,3585000.0,3819000.0,4086000.0,4172693.0,4338977.0,4256013.0,3607000.0,4165416,4552198
114,Europe,Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,...,8012946.0,8310226.0,8576200.0,8797022.0,8892098.0,8971958.0,8658506.0,8066057.0,7661799,7322858
115,Europe,Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,...,4076557.0,4174366.0,4225310.0,4318673.0,4413368.0,4484310.0,4494013.0,4444595.0,4481020,4493312
116,Europe,Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,...,9620282.0,9835109.0,9862158.0,10161915.0,10303704.0,10311597.0,10315702.0,10300707.0,10256295,10228744
117,Europe,Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,...,4646899.0,4838800.0,4991596.0,5088419.0,5117810.0,5127024.0,5171393.0,5283663.0,5374693,5468120
118,Europe,Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,...,4491443.0,4605744.0,4639657.0,4738902.0,4826933.0,4931729.0,5041039.0,5134406.0,5193039,5238460
119,Europe,France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,...,47124000.0,49569000.0,51732000.0,53165019.0,54433565.0,55630100.0,57374179.0,58623428.0,59925035,61083916
120,Europe,Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,...,73739117.0,76368453.0,78717088.0,78160773.0,78335266.0,77718298.0,80597764.0,82011073.0,82350671,82400996
121,Europe,Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,...,8448233.0,8716441.0,8888628.0,9308479.0,9786480.0,9974490.0,10325429.0,10502372.0,10603863,10706290
122,Europe,Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,...,10063000.0,10223422.0,10394091.0,10637171.0,10705535.0,10612740.0,10348684.0,10244684.0,10083313,9956108
123,Europe,Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,...,182053.0,198676.0,209275.0,221823.0,233997.0,244676.0,259012.0,271192.0,288030,301931
124,Europe,Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,...,2830000.0,2900100.0,3024400.0,3271900.0,3480000.0,3539900.0,3557761.0,3667233.0,3879155,4109086
125,Europe,Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,...,50843200.0,52667100.0,54365564.0,56059245.0,56535636.0,56729703.0,56840847.0,57479469.0,57926999,58147733
126,Europe,Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,...,474528.0,501035.0,527678.0,560073.0,562548.0,569473.0,621621.0,692651.0,720230,684736
127,Europe,Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,...,11805689.0,12596822.0,13329874.0,13852989.0,14310401.0,14665278.0,15174244.0,15604464.0,16122830,16570613
128,Europe,Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,...,3638919.0,3786019.0,3933004.0,4043205.0,4114787.0,4186147.0,4286357.0,4405672.0,4535591,4627926
129,Europe,Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,...,30329617.0,31785378.0,33039545.0,34621254.0,36227381.0,37740710.0,38370697.0,38654957.0,38625976,38518241
130,Europe,Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,...,9019800.0,9103000.0,8970450.0,9662600.0,9859650.0,9915289.0,9927680.0,10156415.0,10433867,10642836
131,Europe,Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,...,18680721.0,19284814.0,20662648.0,21658597.0,22356726.0,22686371.0,22797027.0,22562458.0,22404337,22276056
132,Europe,Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,...,7616060.0,7971222.0,8313288.0,8686367.0,9032824.0,9230783.0,9826397.0,10336594.0,10111559,10150265
133,Europe,Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,...,4237384.0,4442238.0,4593433.0,4827803.0,5048043.0,5199318.0,5302888.0,5383010.0,5410052,5447502
134,Europe,Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,...,1582962.0,1646912.0,1694510.0,1746919.0,1861252.0,1945870.0,1999210.0,2011612.0,2011497,2009245
135,Europe,Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,...,31158061.0,32850275.0,34513161.0,36439000.0,37983310.0,38880702.0,39549438.0,39855442.0,40152517,40448191
136,Europe,Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,...,7561588.0,7867931.0,8122293.0,8251648.0,8325260.0,8421403.0,8718867.0,8897619.0,8954175,9031088
137,Europe,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,...,5666000.0,6063000.0,6401400.0,6316424.0,6468126.0,6649942.0,6995447.0,7193761.0,7361757,7554661
138,Europe,Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,...,29788695.0,33411317.0,37492953.0,42404033.0,47328791.0,52881328.0,58179144.0,63047647.0,67308928,71158647
139,Europe,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,...,53292000.0,54959000.0,56079000.0,56179000.0,56339704.0,56981620.0,57866349.0,58808266.0,59912431,60776238
140,Oceania,Australia,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,...,10794968.0,11872264.0,13177000.0,14074100.0,15184200.0,16257249.0,17481977.0,18565243.0,19546792,20434176
141,Oceania,New Zealand,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,...,2488550.0,2728150.0,2929100.0,3164900.0,3210650.0,3317166.0,3437674.0,3676187.0,3908037,4115771

In [119]:
 

#doing a melt function for only pop_year attributes
    
def createString():
    stringsarray = []
    i = 1952
    while(i <2008):
        newstring = 'gdpPercap_'
        newstring +=str(i)
        stringsarray.append(newstring)
        i=i+5
    
    i = 1952
    while(i <2008):
        newstring = 'lifeExp_'
        newstring +=str(i)
        stringsarray.append(newstring)
        i=i+5
    
    
    return stringsarray




id_vars = createString()
id_vars.append("continent")
id_vars.append("country")



df = pd.melt(df, id_vars, var_name="pop_and_year", value_name= "population_")

df

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,...,lifeExp_1982,lifeExp_1987,lifeExp_1992,lifeExp_1997,lifeExp_2002,lifeExp_2007,continent,country,pop_and_year,population_
0,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,...,61.368,65.799,67.744,69.152,70.994,72.301,Africa,Algeria,pop_1952,9279525.0
1,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,...,39.942,39.906,40.647,40.963,41.003,42.731,Africa,Angola,pop_1952,4232095.0
2,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,...,50.904,52.337,53.919,54.777,54.406,56.728,Africa,Benin,pop_1952,1738315.0
3,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,...,61.484,63.622,62.745,52.556,46.634,50.728,Africa,Botswana,pop_1952,442308.0
4,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,...,48.122,49.557,50.260,50.324,50.650,52.295,Africa,Burkina Faso,pop_1952,4469979.0
5,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,...,47.471,48.211,44.736,45.326,47.360,49.580,Africa,Burundi,pop_1952,2445618.0
6,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,...,52.961,54.985,54.314,52.199,49.856,50.430,Africa,Cameroon,pop_1952,5009067.0
7,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,...,48.295,50.485,49.396,46.066,43.308,44.741,Africa,Central African Republic,pop_1952,1291695.0
8,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,...,49.517,51.051,51.724,51.573,50.525,50.651,Africa,Chad,pop_1952,2682462.0
9,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,...,52.933,54.926,57.939,60.660,62.974,65.152,Africa,Comoros,pop_1952,153936.0
10,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,457.719181,312.188423,...,47.784,47.412,45.548,42.587,44.966,46.462,Africa,Congo Dem. Rep.,pop_1952,14100005.0
11,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,4016.239529,3484.164376,...,56.695,57.470,56.433,52.962,52.970,55.322,Africa,Congo Rep.,pop_1952,854885.0
12,1388.594732,1500.895925,1728.869428,2052.050473,2378.201111,2517.736547,2602.710169,2156.956069,1648.073791,1786.265407,...,53.983,54.655,52.044,47.991,46.832,48.328,Africa,Cote d'Ivoire,pop_1952,2977019.0
13,2669.529475,2864.969076,3020.989263,3020.050513,3694.212352,3081.761022,2879.468067,2880.102568,2377.156192,1895.016984,...,48.812,50.040,51.604,53.157,53.373,54.791,Africa,Djibouti,pop_1952,63149.0
14,1418.822445,1458.915272,1693.335853,1814.880728,2024.008147,2785.493582,3503.729636,3885.460710,3794.755195,4173.181797,...,56.006,59.797,63.674,67.217,69.806,71.338,Africa,Egypt,pop_1952,22223309.0
15,375.643123,426.096408,582.841971,915.596003,672.412257,958.566812,927.825343,966.896815,1132.055034,2814.480755,...,43.662,45.664,47.545,48.245,49.348,51.579,Africa,Equatorial Guinea,pop_1952,216964.0
16,328.940557,344.161886,380.995843,468.794970,514.324208,505.753808,524.875849,521.134133,582.858510,913.470790,...,43.890,46.453,49.991,53.378,55.240,58.040,Africa,Eritrea,pop_1952,1438760.0
17,362.146280,378.904163,419.456416,516.118644,566.243944,556.808383,577.860747,573.741314,421.353465,515.889401,...,44.916,46.684,48.091,49.402,50.725,52.947,Africa,Ethiopia,pop_1952,20860941.0
18,4293.476475,4976.198099,6631.459222,8358.761987,11401.948410,21745.573280,15113.361940,11864.408440,13522.157520,14722.841880,...,56.564,60.190,61.366,60.461,56.761,56.735,Africa,Gabon,pop_1952,420702.0
19,485.230659,520.926711,599.650276,734.782912,756.086836,884.755251,835.809611,611.658861,665.624413,653.730170,...,45.580,49.265,52.644,55.861,58.041,59.448,Africa,Gambia,pop_1952,284320.0
20,911.298937,1043.561537,1190.041118,1125.697160,1178.223708,993.223957,876.032569,847.006113,925.060154,1005.245812,...,53.744,55.729,57.501,58.556,58.453,60.022,Africa,Ghana,pop_1952,5581001.0
21,510.196492,576.267025,686.373674,708.759541,741.666231,874.685864,857.250358,805.572472,794.348438,869.449767,...,42.891,45.552,48.576,51.455,53.676,56.007,Africa,Guinea,pop_1952,2664249.0
22,299.850319,431.790457,522.034373,715.580640,820.224588,764.725963,838.123967,736.415392,745.539871,796.664468,...,39.327,41.245,43.266,44.873,45.504,46.388,Africa,Guinea-Bissau,pop_1952,580653.0
23,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,1341.921721,1360.485021,...,58.766,59.339,59.285,54.407,50.992,54.110,Africa,Kenya,pop_1952,6464046.0
24,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,977.486272,1186.147994,...,55.078,57.180,59.685,55.558,44.593,42.592,Africa,Lesotho,pop_1952,748747.0
25,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,636.622919,609.173951,...,44.852,46.027,40.802,42.221,43.753,45.678,Africa,Liberia,pop_1952,863308.0
26,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,9640.138501,9467.446056,...,62.155,66.234,68.755,71.555,72.737,73.952,Africa,Libya,pop_1952,1019729.0
27,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,1040.676190,986.295896,...,48.969,49.350,52.214,54.978,57.286,59.443,Africa,Madagascar,pop_1952,4762912.0
28,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,563.200014,692.275810,...,45.642,47.457,49.420,47.495,45.009,48.303,Africa,Malawi,pop_1952,2917802.0
29,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,739.014375,790.257985,...,43.916,46.364,48.388,49.903,51.818,54.467,Africa,Mali,pop_1952,3838168.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,...,73.930,75.350,76.460,77.530,78.320,79.441,Europe,Belgium,pop_2007,10392226.0
1675,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,...,70.690,71.140,72.178,73.244,74.090,74.852,Europe,Bosnia and Herzegovina,pop_2007,4552198.0
1676,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,...,71.080,71.340,71.190,70.320,72.140,73.005,Europe,Bulgaria,pop_2007,7322858.0
1677,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,...,70.460,71.520,72.527,73.680,74.876,75.748,Europe,Croatia,pop_2007,4493312.0
1678,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,...,70.960,71.580,72.400,74.010,75.510,76.486,Europe,Czech Republic,pop_2007,10228744.0
1679,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,...,74.630,74.800,75.330,76.110,77.180,78.332,Europe,Denmark,pop_2007,5468120.0
1680,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,...,74.550,74.830,75.700,77.130,78.370,79.313,Europe,Finland,pop_2007,5238460.0
1681,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,...,74.890,76.340,77.460,78.640,79.590,80.657,Europe,France,pop_2007,61083916.0
1682,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,...,73.800,74.847,76.070,77.340,78.670,79.406,Europe,Germany,pop_2007,82400996.0
1683,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,...,75.240,76.670,77.030,77.869,78.256,79.483,Europe,Greece,pop_2007,10706290.0
1684,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,...,69.390,69.580,69.170,71.040,72.590,73.338,Europe,Hungary,pop_2007,9956108.0
1685,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,...,76.990,77.230,78.770,78.950,80.500,81.757,Europe,Iceland,pop_2007,301931.0
1686,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,...,73.100,74.360,75.467,76.122,77.783,78.885,Europe,Ireland,pop_2007,4109086.0
1687,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,...,74.980,76.420,77.440,78.820,80.240,80.546,Europe,Italy,pop_2007,58147733.0
1688,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,...,74.101,74.865,75.435,75.445,73.981,74.543,Europe,Montenegro,pop_2007,684736.0
1689,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,...,76.050,76.830,77.420,78.030,78.530,79.762,Europe,Netherlands,pop_2007,16570613.0
1690,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,...,75.970,75.890,77.320,78.320,79.050,80.196,Europe,Norway,pop_2007,4627926.0
1691,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,...,71.320,70.980,70.990,72.750,74.670,75.563,Europe,Poland,pop_2007,38518241.0
1692,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,...,72.770,74.060,74.860,75.970,77.290,78.098,Europe,Portugal,pop_2007,10642836.0
1693,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,...,69.660,69.530,69.360,69.720,71.322,72.476,Europe,Romania,pop_2007,22276056.0
1694,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,...,70.162,71.218,71.659,72.232,73.213,74.002,Europe,Serbia,pop_2007,10150265.0
1695,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,...,70.800,71.080,71.380,72.710,73.800,74.663,Europe,Slovak Republic,pop_2007,5447502.0
1696,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,...,71.063,72.250,73.640,75.130,76.660,77.926,Europe,Slovenia,pop_2007,2009245.0
1697,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,...,76.300,76.900,77.570,78.770,79.780,80.941,Europe,Spain,pop_2007,40448191.0
1698,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,...,76.420,77.190,78.160,79.390,80.040,80.884,Europe,Sweden,pop_2007,9031088.0
1699,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,...,76.210,77.410,78.030,79.370,80.620,81.701,Europe,Switzerland,pop_2007,7554661.0
1700,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,...,61.036,63.108,66.146,68.835,70.845,71.777,Europe,Turkey,pop_2007,71158647.0
1701,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,...,74.040,75.007,76.420,77.218,78.471,79.425,Europe,United Kingdom,pop_2007,60776238.0
1702,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,26997.936570,...,74.740,76.320,77.560,78.830,80.370,81.235,Oceania,Australia,pop_2007,20434176.0
1703,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,18363.324940,21050.413770,...,73.840,74.320,76.330,77.550,79.110,80.204,Oceania,New Zealand,pop_2007,4115771.0

In [120]:
#doing a melt function for life expectancy values
def createString():
    stringsarray = []
    i = 1952
    while(i <2008):
        newstring = 'gdpPercap_'
        newstring +=str(i)
        stringsarray.append(newstring)
        i=i+5

    return stringsarray



id_vars = createString()
id_vars.append("continent")
id_vars.append("country")
id_vars.append("pop_and_year")
id_vars.append("population_")

df = pd.melt(df, id_vars, var_name="lifeExp_and_year", value_name = "life_expectancy")
df

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,continent,country,pop_and_year,population_,lifeExp_and_year,life_expectancy
0,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465,Africa,Algeria,pop_1952,9279525.0,lifeExp_1952,43.077
1,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267,Africa,Angola,pop_1952,4232095.0,lifeExp_1952,30.015
2,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873,Africa,Benin,pop_1952,1738315.0,lifeExp_1952,38.223
3,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770,Africa,Botswana,pop_1952,442308.0,lifeExp_1952,47.622
4,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994,Africa,Burkina Faso,pop_1952,4469979.0,lifeExp_1952,31.975
5,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,446.403513,430.070692,Africa,Burundi,pop_1952,2445618.0,lifeExp_1952,39.031
6,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,1934.011449,2042.095240,Africa,Cameroon,pop_1952,5009067.0,lifeExp_1952,38.523
7,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,738.690607,706.016537,Africa,Central African Republic,pop_1952,1291695.0,lifeExp_1952,35.463
8,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,1156.181860,1704.063724,Africa,Chad,pop_1952,2682462.0,lifeExp_1952,38.092
9,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,1075.811558,986.147879,Africa,Comoros,pop_1952,153936.0,lifeExp_1952,40.715
10,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,457.719181,312.188423,241.165877,277.551859,Africa,Congo Dem. Rep.,pop_1952,14100005.0,lifeExp_1952,39.143
11,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,4016.239529,3484.164376,3484.061970,3632.557798,Africa,Congo Rep.,pop_1952,854885.0,lifeExp_1952,42.111
12,1388.594732,1500.895925,1728.869428,2052.050473,2378.201111,2517.736547,2602.710169,2156.956069,1648.073791,1786.265407,1648.800823,1544.750112,Africa,Cote d'Ivoire,pop_1952,2977019.0,lifeExp_1952,40.477
13,2669.529475,2864.969076,3020.989263,3020.050513,3694.212352,3081.761022,2879.468067,2880.102568,2377.156192,1895.016984,1908.260867,2082.481567,Africa,Djibouti,pop_1952,63149.0,lifeExp_1952,34.812
14,1418.822445,1458.915272,1693.335853,1814.880728,2024.008147,2785.493582,3503.729636,3885.460710,3794.755195,4173.181797,4754.604414,5581.180998,Africa,Egypt,pop_1952,22223309.0,lifeExp_1952,41.893
15,375.643123,426.096408,582.841971,915.596003,672.412257,958.566812,927.825343,966.896815,1132.055034,2814.480755,7703.495900,12154.089750,Africa,Equatorial Guinea,pop_1952,216964.0,lifeExp_1952,34.482
16,328.940557,344.161886,380.995843,468.794970,514.324208,505.753808,524.875849,521.134133,582.858510,913.470790,765.350001,641.369524,Africa,Eritrea,pop_1952,1438760.0,lifeExp_1952,35.928
17,362.146280,378.904163,419.456416,516.118644,566.243944,556.808383,577.860747,573.741314,421.353465,515.889401,530.053532,690.805576,Africa,Ethiopia,pop_1952,20860941.0,lifeExp_1952,34.078
18,4293.476475,4976.198099,6631.459222,8358.761987,11401.948410,21745.573280,15113.361940,11864.408440,13522.157520,14722.841880,12521.713920,13206.484520,Africa,Gabon,pop_1952,420702.0,lifeExp_1952,37.003
19,485.230659,520.926711,599.650276,734.782912,756.086836,884.755251,835.809611,611.658861,665.624413,653.730170,660.585600,752.749726,Africa,Gambia,pop_1952,284320.0,lifeExp_1952,30.000
20,911.298937,1043.561537,1190.041118,1125.697160,1178.223708,993.223957,876.032569,847.006113,925.060154,1005.245812,1111.984578,1327.608910,Africa,Ghana,pop_1952,5581001.0,lifeExp_1952,43.149
21,510.196492,576.267025,686.373674,708.759541,741.666231,874.685864,857.250358,805.572472,794.348438,869.449767,945.583584,942.654211,Africa,Guinea,pop_1952,2664249.0,lifeExp_1952,33.609
22,299.850319,431.790457,522.034373,715.580640,820.224588,764.725963,838.123967,736.415392,745.539871,796.664468,575.704718,579.231743,Africa,Guinea-Bissau,pop_1952,580653.0,lifeExp_1952,32.500
23,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,1341.921721,1360.485021,1287.514732,1463.249282,Africa,Kenya,pop_1952,6464046.0,lifeExp_1952,42.270
24,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,977.486272,1186.147994,1275.184575,1569.331442,Africa,Lesotho,pop_1952,748747.0,lifeExp_1952,42.138
25,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,636.622919,609.173951,531.482368,414.507341,Africa,Liberia,pop_1952,863308.0,lifeExp_1952,38.480
26,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,9640.138501,9467.446056,9534.677467,12057.499280,Africa,Libya,pop_1952,1019729.0,lifeExp_1952,42.723
27,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,1040.676190,986.295896,894.637082,1044.770126,Africa,Madagascar,pop_1952,4762912.0,lifeExp_1952,36.681
28,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,563.200014,692.275810,665.423119,759.349910,Africa,Malawi,pop_1952,2917802.0,lifeExp_1952,36.256
29,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,739.014375,790.257985,951.409752,1042.581557,Africa,Mali,pop_1952,3838168.0,lifeExp_1952,33.685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20418,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080,Europe,Belgium,pop_2007,10392226.0,lifeExp_2007,79.441
20419,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803,Europe,Bosnia and Herzegovina,pop_2007,4552198.0,lifeExp_2007,74.852
20420,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820,Europe,Bulgaria,pop_2007,7322858.0,lifeExp_2007,73.005
20421,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720,Europe,Croatia,pop_2007,4493312.0,lifeExp_2007,75.748
20422,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510,Europe,Czech Republic,pop_2007,10228744.0,lifeExp_2007,76.486
20423,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740,Europe,Denmark,pop_2007,5468120.0,lifeExp_2007,78.332
20424,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400,Europe,Finland,pop_2007,5238460.0,lifeExp_2007,79.313
20425,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700,Europe,France,pop_2007,61083916.0,lifeExp_2007,80.657
20426,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420,Europe,Germany,pop_2007,82400996.0,lifeExp_2007,79.406
20427,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880,Europe,Greece,pop_2007,10706290.0,lifeExp_2007,79.483
20428,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440,Europe,Hungary,pop_2007,9956108.0,lifeExp_2007,73.338
20429,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190,Europe,Iceland,pop_2007,301931.0,lifeExp_2007,81.757
20430,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350,Europe,Ireland,pop_2007,4109086.0,lifeExp_2007,78.885
20431,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700,Europe,Italy,pop_2007,58147733.0,lifeExp_2007,80.546
20432,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111,Europe,Montenegro,pop_2007,684736.0,lifeExp_2007,74.543
20433,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320,Europe,Netherlands,pop_2007,16570613.0,lifeExp_2007,79.762
20434,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170,Europe,Norway,pop_2007,4627926.0,lifeExp_2007,80.196
20435,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680,Europe,Poland,pop_2007,38518241.0,lifeExp_2007,75.563
20436,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770,Europe,Portugal,pop_2007,10642836.0,lifeExp_2007,78.098
20437,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610,Europe,Romania,pop_2007,22276056.0,lifeExp_2007,72.476
20438,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714,Europe,Serbia,pop_2007,10150265.0,lifeExp_2007,74.002
20439,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350,Europe,Slovak Republic,pop_2007,5447502.0,lifeExp_2007,74.663
20440,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590,Europe,Slovenia,pop_2007,2009245.0,lifeExp_2007,77.926
20441,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700,Europe,Spain,pop_2007,40448191.0,lifeExp_2007,80.941
20442,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350,Europe,Sweden,pop_2007,9031088.0,lifeExp_2007,80.884
20443,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070,Europe,Switzerland,pop_2007,7554661.0,lifeExp_2007,81.701
20444,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384,Europe,Turkey,pop_2007,71158647.0,lifeExp_2007,71.777
20445,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280,Europe,United Kingdom,pop_2007,60776238.0,lifeExp_2007,79.425
20446,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,26997.936570,30687.754730,34435.367440,Oceania,Australia,pop_2007,20434176.0,lifeExp_2007,81.235
20447,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,18363.324940,21050.413770,23189.801350,25185.009110,Oceania,New Zealand,pop_2007,4115771.0,lifeExp_2007,80.204

In [121]:
#doing a melt function for gdpperCapita values

id_vars = []
id_vars.append("continent")
id_vars.append("country")
id_vars.append("pop_and_year")
id_vars.append("population_")
id_vars.append("lifeExp_and_year")
id_vars.append("life_expectancy")

df = pd.melt(df, id_vars, var_name="gdpPercap_and_year", value_name = "gdpPercap")
df

,continent,country,pop_and_year,population_,lifeExp_and_year,life_expectancy,gdpPercap_and_year,gdpPercap
0,Africa,Algeria,pop_1952,9279525.0,lifeExp_1952,43.077,gdpPercap_1952,2449.008185
1,Africa,Angola,pop_1952,4232095.0,lifeExp_1952,30.015,gdpPercap_1952,3520.610273
2,Africa,Benin,pop_1952,1738315.0,lifeExp_1952,38.223,gdpPercap_1952,1062.752200
3,Africa,Botswana,pop_1952,442308.0,lifeExp_1952,47.622,gdpPercap_1952,851.241141
4,Africa,Burkina Faso,pop_1952,4469979.0,lifeExp_1952,31.975,gdpPercap_1952,543.255241
5,Africa,Burundi,pop_1952,2445618.0,lifeExp_1952,39.031,gdpPercap_1952,339.296459
6,Africa,Cameroon,pop_1952,5009067.0,lifeExp_1952,38.523,gdpPercap_1952,1172.667655
7,Africa,Central African Republic,pop_1952,1291695.0,lifeExp_1952,35.463,gdpPercap_1952,1071.310713
8,Africa,Chad,pop_1952,2682462.0,lifeExp_1952,38.092,gdpPercap_1952,1178.665927
9,Africa,Comoros,pop_1952,153936.0,lifeExp_1952,40.715,gdpPercap_1952,1102.990936
10,Africa,Congo Dem. Rep.,pop_1952,14100005.0,lifeExp_1952,39.143,gdpPercap_1952,780.542326
11,Africa,Congo Rep.,pop_1952,854885.0,lifeExp_1952,42.111,gdpPercap_1952,2125.621418
12,Africa,Cote d'Ivoire,pop_1952,2977019.0,lifeExp_1952,40.477,gdpPercap_1952,1388.594732
13,Africa,Djibouti,pop_1952,63149.0,lifeExp_1952,34.812,gdpPercap_1952,2669.529475
14,Africa,Egypt,pop_1952,22223309.0,lifeExp_1952,41.893,gdpPercap_1952,1418.822445
15,Africa,Equatorial Guinea,pop_1952,216964.0,lifeExp_1952,34.482,gdpPercap_1952,375.643123
16,Africa,Eritrea,pop_1952,1438760.0,lifeExp_1952,35.928,gdpPercap_1952,328.940557
17,Africa,Ethiopia,pop_1952,20860941.0,lifeExp_1952,34.078,gdpPercap_1952,362.146280
18,Africa,Gabon,pop_1952,420702.0,lifeExp_1952,37.003,gdpPercap_1952,4293.476475
19,Africa,Gambia,pop_1952,284320.0,lifeExp_1952,30.000,gdpPercap_1952,485.230659
20,Africa,Ghana,pop_1952,5581001.0,lifeExp_1952,43.149,gdpPercap_1952,911.298937
21,Africa,Guinea,pop_1952,2664249.0,lifeExp_1952,33.609,gdpPercap_1952,510.196492
22,Africa,Guinea-Bissau,pop_1952,580653.0,lifeExp_1952,32.500,gdpPercap_1952,299.850319
23,Africa,Kenya,pop_1952,6464046.0,lifeExp_1952,42.270,gdpPercap_1952,853.540919
24,Africa,Lesotho,pop_1952,748747.0,lifeExp_1952,42.138,gdpPercap_1952,298.846212
25,Africa,Liberia,pop_1952,863308.0,lifeExp_1952,38.480,gdpPercap_1952,575.572996
26,Africa,Libya,pop_1952,1019729.0,lifeExp_1952,42.723,gdpPercap_1952,2387.548060
27,Africa,Madagascar,pop_1952,4762912.0,lifeExp_1952,36.681,gdpPercap_1952,1443.011715
28,Africa,Malawi,pop_1952,2917802.0,lifeExp_1952,36.256,gdpPercap_1952,369.165080
29,Africa,Mali,pop_1952,3838168.0,lifeExp_1952,33.685,gdpPercap_1952,452.336981
...,...,...,...,...,...,...,...,...
245346,Europe,Belgium,pop_2007,10392226.0,lifeExp_2007,79.441,gdpPercap_2007,33692.605080
245347,Europe,Bosnia and Herzegovina,pop_2007,4552198.0,lifeExp_2007,74.852,gdpPercap_2007,7446.298803
245348,Europe,Bulgaria,pop_2007,7322858.0,lifeExp_2007,73.005,gdpPercap_2007,10680.792820
245349,Europe,Croatia,pop_2007,4493312.0,lifeExp_2007,75.748,gdpPercap_2007,14619.222720
245350,Europe,Czech Republic,pop_2007,10228744.0,lifeExp_2007,76.486,gdpPercap_2007,22833.308510
245351,Europe,Denmark,pop_2007,5468120.0,lifeExp_2007,78.332,gdpPercap_2007,35278.418740
245352,Europe,Finland,pop_2007,5238460.0,lifeExp_2007,79.313,gdpPercap_2007,33207.084400
245353,Europe,France,pop_2007,61083916.0,lifeExp_2007,80.657,gdpPercap_2007,30470.016700
245354,Europe,Germany,pop_2007,82400996.0,lifeExp_2007,79.406,gdpPercap_2007,32170.374420
245355,Europe,Greece,pop_2007,10706290.0,lifeExp_2007,79.483,gdpPercap_2007,27538.411880
245356,Europe,Hungary,pop_2007,9956108.0,lifeExp_2007,73.338,gdpPercap_2007,18008.944440
245357,Europe,Iceland,pop_2007,301931.0,lifeExp_2007,81.757,gdpPercap_2007,36180.789190
245358,Europe,Ireland,pop_2007,4109086.0,lifeExp_2007,78.885,gdpPercap_2007,40675.996350
245359,Europe,Italy,pop_2007,58147733.0,lifeExp_2007,80.546,gdpPercap_2007,28569.719700
245360,Europe,Montenegro,pop_2007,684736.0,lifeExp_2007,74.543,gdpPercap_2007,9253.896111
245361,Europe,Netherlands,pop_2007,16570613.0,lifeExp_2007,79.762,gdpPercap_2007,36797.933320
245362,Europe,Norway,pop_2007,4627926.0,lifeExp_2007,80.196,gdpPercap_2007,49357.190170
245363,Europe,Poland,pop_2007,38518241.0,lifeExp_2007,75.563,gdpPercap_2007,15389.924680
245364,Europe,Portugal,pop_2007,10642836.0,lifeExp_2007,78.098,gdpPercap_2007,20509.647770
245365,Europe,Romania,pop_2007,22276056.0,lifeExp_2007,72.476,gdpPercap_2007,10808.475610
245366,Europe,Serbia,pop_2007,10150265.0,lifeExp_2007,74.002,gdpPercap_2007,9786.534714
245367,Europe,Slovak Republic,pop_2007,5447502.0,lifeExp_2007,74.663,gdpPercap_2007,18678.314350
245368,Europe,Slovenia,pop_2007,2009245.0,lifeExp_2007,77.926,gdpPercap_2007,25768.257590
245369,Europe,Spain,pop_2007,40448191.0,lifeExp_2007,80.941,gdpPercap_2007,28821.063700
245370,Europe,Sweden,pop_2007,9031088.0,lifeExp_2007,80.884,gdpPercap_2007,33859.748350
245371,Europe,Switzerland,pop_2007,7554661.0,lifeExp_2007,81.701,gdpPercap_2007,37506.419070
245372,Europe,Turkey,pop_2007,71158647.0,lifeExp_2007,71.777,gdpPercap_2007,8458.276384
245373,Europe,United Kingdom,pop_2007,60776238.0,lifeExp_2007,79.425,gdpPercap_2007,33203.261280
245374,Oceania,Australia,pop_2007,20434176.0,lifeExp_2007,81.235,gdpPercap_2007,34435.367440
245375,Oceania,New Zealand,pop_2007,4115771.0,lifeExp_2007,80.204,gdpPercap_2007,25185.009110

In [122]:
new_df = df

In [129]:
new_df['year'] = new_df['pop_and_year'].str.extract(pat = '([1|2]...)') 

new_df['year']

0         1952
1         1952
2         1952
3         1952
4         1952
5         1952
6         1952
7         1952
8         1952
9         1952
10        1952
11        1952
12        1952
13        1952
14        1952
15        1952
16        1952
17        1952
18        1952
19        1952
20        1952
21        1952
22        1952
23        1952
24        1952
25        1952
26        1952
27        1952
28        1952
29        1952
          ...
245346    2007
245347    2007
245348    2007
245349    2007
245350    2007
245351    2007
245352    2007
245353    2007
245354    2007
245355    2007
245356    2007
245357    2007
245358    2007
245359    2007
245360    2007
245361    2007
245362    2007
245363    2007
245364    2007
245365    2007
245366    2007
245367    2007
245368    2007
245369    2007
245370    2007
245371    2007
245372    2007
245373    2007
245374    2007
245375    2007
Name: year, Length: 245376, dtype: object

In [130]:
new_df

,continent,country,pop_and_year,population_,lifeExp_and_year,life_expectancy,gdpPercap_and_year,gdpPercap,extraction,year
0,Africa,Algeria,pop_1952,9279525.0,lifeExp_1952,43.077,gdpPercap_1952,2449.008185,1952,1952
1,Africa,Angola,pop_1952,4232095.0,lifeExp_1952,30.015,gdpPercap_1952,3520.610273,1952,1952
2,Africa,Benin,pop_1952,1738315.0,lifeExp_1952,38.223,gdpPercap_1952,1062.752200,1952,1952
3,Africa,Botswana,pop_1952,442308.0,lifeExp_1952,47.622,gdpPercap_1952,851.241141,1952,1952
4,Africa,Burkina Faso,pop_1952,4469979.0,lifeExp_1952,31.975,gdpPercap_1952,543.255241,1952,1952
5,Africa,Burundi,pop_1952,2445618.0,lifeExp_1952,39.031,gdpPercap_1952,339.296459,1952,1952
6,Africa,Cameroon,pop_1952,5009067.0,lifeExp_1952,38.523,gdpPercap_1952,1172.667655,1952,1952
7,Africa,Central African Republic,pop_1952,1291695.0,lifeExp_1952,35.463,gdpPercap_1952,1071.310713,1952,1952
8,Africa,Chad,pop_1952,2682462.0,lifeExp_1952,38.092,gdpPercap_1952,1178.665927,1952,1952
9,Africa,Comoros,pop_1952,153936.0,lifeExp_1952,40.715,gdpPercap_1952,1102.990936,1952,1952
10,Africa,Congo Dem. Rep.,pop_1952,14100005.0,lifeExp_1952,39.143,gdpPercap_1952,780.542326,1952,1952
11,Africa,Congo Rep.,pop_1952,854885.0,lifeExp_1952,42.111,gdpPercap_1952,2125.621418,1952,1952
12,Africa,Cote d'Ivoire,pop_1952,2977019.0,lifeExp_1952,40.477,gdpPercap_1952,1388.594732,1952,1952
13,Africa,Djibouti,pop_1952,63149.0,lifeExp_1952,34.812,gdpPercap_1952,2669.529475,1952,1952
14,Africa,Egypt,pop_1952,22223309.0,lifeExp_1952,41.893,gdpPercap_1952,1418.822445,1952,1952
15,Africa,Equatorial Guinea,pop_1952,216964.0,lifeExp_1952,34.482,gdpPercap_1952,375.643123,1952,1952
16,Africa,Eritrea,pop_1952,1438760.0,lifeExp_1952,35.928,gdpPercap_1952,328.940557,1952,1952
17,Africa,Ethiopia,pop_1952,20860941.0,lifeExp_1952,34.078,gdpPercap_1952,362.146280,1952,1952
18,Africa,Gabon,pop_1952,420702.0,lifeExp_1952,37.003,gdpPercap_1952,4293.476475,1952,1952
19,Africa,Gambia,pop_1952,284320.0,lifeExp_1952,30.000,gdpPercap_1952,485.230659,1952,1952
20,Africa,Ghana,pop_1952,5581001.0,lifeExp_1952,43.149,gdpPercap_1952,911.298937,1952,1952
21,Africa,Guinea,pop_1952,2664249.0,lifeExp_1952,33.609,gdpPercap_1952,510.196492,1952,1952
22,Africa,Guinea-Bissau,pop_1952,580653.0,lifeExp_1952,32.500,gdpPercap_1952,299.850319,1952,1952
23,Africa,Kenya,pop_1952,6464046.0,lifeExp_1952,42.270,gdpPercap_1952,853.540919,1952,1952
24,Africa,Lesotho,pop_1952,748747.0,lifeExp_1952,42.138,gdpPercap_1952,298.846212,1952,1952
25,Africa,Liberia,pop_1952,863308.0,lifeExp_1952,38.480,gdpPercap_1952,575.572996,1952,1952
26,Africa,Libya,pop_1952,1019729.0,lifeExp_1952,42.723,gdpPercap_1952,2387.548060,1952,1952
27,Africa,Madagascar,pop_1952,4762912.0,lifeExp_1952,36.681,gdpPercap_1952,1443.011715,1952,1952
28,Africa,Malawi,pop_1952,2917802.0,lifeExp_1952,36.256,gdpPercap_1952,369.165080,1952,1952
29,Africa,Mali,pop_1952,3838168.0,lifeExp_1952,33.685,gdpPercap_1952,452.336981,1952,1952
...,...,...,...,...,...,...,...,...,...,...
245346,Europe,Belgium,pop_2007,10392226.0,lifeExp_2007,79.441,gdpPercap_2007,33692.605080,2007,2007
245347,Europe,Bosnia and Herzegovina,pop_2007,4552198.0,lifeExp_2007,74.852,gdpPercap_2007,7446.298803,2007,2007
245348,Europe,Bulgaria,pop_2007,7322858.0,lifeExp_2007,73.005,gdpPercap_2007,10680.792820,2007,2007
245349,Europe,Croatia,pop_2007,4493312.0,lifeExp_2007,75.748,gdpPercap_2007,14619.222720,2007,2007
245350,Europe,Czech Republic,pop_2007,10228744.0,lifeExp_2007,76.486,gdpPercap_2007,22833.308510,2007,2007
245351,Europe,Denmark,pop_2007,5468120.0,lifeExp_2007,78.332,gdpPercap_2007,35278.418740,2007,2007
245352,Europe,Finland,pop_2007,5238460.0,lifeExp_2007,79.313,gdpPercap_2007,33207.084400,2007,2007
245353,Europe,France,pop_2007,61083916.0,lifeExp_2007,80.657,gdpPercap_2007,30470.016700,2007,2007
245354,Europe,Germany,pop_2007,82400996.0,lifeExp_2007,79.406,gdpPercap_2007,32170.374420,2007,2007
245355,Europe,Greece,pop_2007,10706290.0,lifeExp_2007,79.483,gdpPercap_2007,27538.411880,2007,2007
245356,Europe,Hungary,pop_2007,9956108.0,lifeExp_2007,73.338,gdpPercap_2007,18008.944440,2007,2007
245357,Europe,Iceland,pop_2007,301931.0,lifeExp_2007,81.757,gdpPercap_2007,36180.789190,2007,2007
245358,Europe,Ireland,pop_2007,4109086.0,lifeExp_2007,78.885,gdpPercap_2007,40675.996350,2007,2007
245359,Europe,Italy,pop_2007,58147733.0,lifeExp_2007,80.546,gdpPercap_2007,28569.719700,2007,2007
245360,Europe,Montenegro,pop_2007,684736.0,lifeExp_2007,74.543,gdpPercap_2007,9253.896111,2007,2007
245361,Europe,Netherlands,pop_2007,16570613.0,lifeExp_2007,79.762,gdpPercap_2007,36797.933320,2007,2007
245362,Europe,Norway,pop_2007,4627926.0,lifeExp_2007,80.196,gdpPercap_2007,49357.190170,2007,2007
245363,Europe,Poland,pop_2007,38518241.0,lifeExp_2007,75.563,gdpPercap_2007,15389.924680,2007,2007
245364,Europe,Portugal,pop_2007,10642836.0,lifeExp_2007,78.098,gdpPercap_2007,20509.647770,2007,2007
245365,Europe,Romania,pop_2007,22276056.0,lifeExp_2007,72.476,gdpPercap_2007,10808.475610,2007,2007
245366,Europe,Serbia,pop_2007,10150265.0,lifeExp_2007,74.002,gdpPercap_2007,9786.534714,2007,2007
245367,Europe,Slovak Republic,pop_2007,5447502.0,lifeExp_2007,74.663,gdpPercap_2007,18678.314350,2007,2007
245368,Europe,Slovenia,pop_2007,2009245.0,lifeExp_2007,77.926,gdpPercap_2007,25768.257590,2007,2007
245369,Europe,Spain,pop_2007,40448191.0,lifeExp_2007,80.941,gdpPercap_2007,28821.063700,2007,2007
245370,Europe,Sweden,pop_2007,9031088.0,lifeExp_2007,80.884,gdpPercap_2007,33859.748350,2007,2007
245371,Europe,Switzerland,pop_2007,7554661.0,lifeExp_2007,81.701,gdpPercap_2007,37506.419070,2007,2007
245372,Europe,Turkey,pop_2007,71158647.0,lifeExp_2007,71.777,gdpPercap_2007,8458.276384,2007,2007
245373,Europe,United Kingdom,pop_2007,60776238.0,lifeExp_2007,79.425,gdpPercap_2007,33203.261280,2007,2007
245374,Oceania,Australia,pop_2007,20434176.0,lifeExp_2007,81.235,gdpPercap_2007,34435.367440,2007,2007
245375,Oceania,New Zealand,pop_2007,4115771.0,lifeExp_2007,80.204,gdpPercap_2007,25185.009110,2007,2007

In [131]:
new_df = new_df.drop(['pop_and_year',"lifeExp_and_year","gdpPercap_and_year", "extraction"], axis=1)
new_df

,continent,country,population_,life_expectancy,gdpPercap,year
0,Africa,Algeria,9279525.0,43.077,2449.008185,1952
1,Africa,Angola,4232095.0,30.015,3520.610273,1952
2,Africa,Benin,1738315.0,38.223,1062.752200,1952
3,Africa,Botswana,442308.0,47.622,851.241141,1952
4,Africa,Burkina Faso,4469979.0,31.975,543.255241,1952
5,Africa,Burundi,2445618.0,39.031,339.296459,1952
6,Africa,Cameroon,5009067.0,38.523,1172.667655,1952
7,Africa,Central African Republic,1291695.0,35.463,1071.310713,1952
8,Africa,Chad,2682462.0,38.092,1178.665927,1952
9,Africa,Comoros,153936.0,40.715,1102.990936,1952
10,Africa,Congo Dem. Rep.,14100005.0,39.143,780.542326,1952
11,Africa,Congo Rep.,854885.0,42.111,2125.621418,1952
12,Africa,Cote d'Ivoire,2977019.0,40.477,1388.594732,1952
13,Africa,Djibouti,63149.0,34.812,2669.529475,1952
14,Africa,Egypt,22223309.0,41.893,1418.822445,1952
15,Africa,Equatorial Guinea,216964.0,34.482,375.643123,1952
16,Africa,Eritrea,1438760.0,35.928,328.940557,1952
17,Africa,Ethiopia,20860941.0,34.078,362.146280,1952
18,Africa,Gabon,420702.0,37.003,4293.476475,1952
19,Africa,Gambia,284320.0,30.000,485.230659,1952
20,Africa,Ghana,5581001.0,43.149,911.298937,1952
21,Africa,Guinea,2664249.0,33.609,510.196492,1952
22,Africa,Guinea-Bissau,580653.0,32.500,299.850319,1952
23,Africa,Kenya,6464046.0,42.270,853.540919,1952
24,Africa,Lesotho,748747.0,42.138,298.846212,1952
25,Africa,Liberia,863308.0,38.480,575.572996,1952
26,Africa,Libya,1019729.0,42.723,2387.548060,1952
27,Africa,Madagascar,4762912.0,36.681,1443.011715,1952
28,Africa,Malawi,2917802.0,36.256,369.165080,1952
29,Africa,Mali,3838168.0,33.685,452.336981,1952
...,...,...,...,...,...,...
245346,Europe,Belgium,10392226.0,79.441,33692.605080,2007
245347,Europe,Bosnia and Herzegovina,4552198.0,74.852,7446.298803,2007
245348,Europe,Bulgaria,7322858.0,73.005,10680.792820,2007
245349,Europe,Croatia,4493312.0,75.748,14619.222720,2007
245350,Europe,Czech Republic,10228744.0,76.486,22833.308510,2007
245351,Europe,Denmark,5468120.0,78.332,35278.418740,2007
245352,Europe,Finland,5238460.0,79.313,33207.084400,2007
245353,Europe,France,61083916.0,80.657,30470.016700,2007
245354,Europe,Germany,82400996.0,79.406,32170.374420,2007
245355,Europe,Greece,10706290.0,79.483,27538.411880,2007
245356,Europe,Hungary,9956108.0,73.338,18008.944440,2007
245357,Europe,Iceland,301931.0,81.757,36180.789190,2007
245358,Europe,Ireland,4109086.0,78.885,40675.996350,2007
245359,Europe,Italy,58147733.0,80.546,28569.719700,2007
245360,Europe,Montenegro,684736.0,74.543,9253.896111,2007
245361,Europe,Netherlands,16570613.0,79.762,36797.933320,2007
245362,Europe,Norway,4627926.0,80.196,49357.190170,2007
245363,Europe,Poland,38518241.0,75.563,15389.924680,2007
245364,Europe,Portugal,10642836.0,78.098,20509.647770,2007
245365,Europe,Romania,22276056.0,72.476,10808.475610,2007
245366,Europe,Serbia,10150265.0,74.002,9786.534714,2007
245367,Europe,Slovak Republic,5447502.0,74.663,18678.314350,2007
245368,Europe,Slovenia,2009245.0,77.926,25768.257590,2007
245369,Europe,Spain,40448191.0,80.941,28821.063700,2007
245370,Europe,Sweden,9031088.0,80.884,33859.748350,2007
245371,Europe,Switzerland,7554661.0,81.701,37506.419070,2007
245372,Europe,Turkey,71158647.0,71.777,8458.276384,2007
245373,Europe,United Kingdom,60776238.0,79.425,33203.261280,2007
245374,Oceania,Australia,20434176.0,81.235,34435.367440,2007
245375,Oceania,New Zealand,4115771.0,80.204,25185.009110,2007